apiVersion: apps/v1
kind: Deployment
metadata:
   name: springboot-k8s-deploy
   labels:
      app: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      name: insurance
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: spring-boot-k8s
        image: ssahu1/insurance-proj:v1.38
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-svc
spec:
  type: NodePort
  selector:
    app: spring-boot-k8s
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
